#!/bin/bash
# This script is released under the GNU General Public License 3.0
# Check the COPYING file included with this distribution

# pentoo-installer
# main menu for the installation
# sub scripts should write only results to STDOUT
# menus and noise go to STDERR
# params: none
#
# returns 0 on success
# returns $ERROR_CANCEL=64 on user cancel
# anything else is a real error
# reason: show_dialog() needs a way to exit "Cancel"
#

readonly SHAREDIR="$(dirname ${0})/../share/pentoo-installer"

# source common variables, functions and error handling
# also get functions to save settings
source "${SHAREDIR}"/save_settings.sh || exit $?

#####################
## begin execution ##

## start by exiting if the user doesn't have enough RAM for the install to work
RAMSIZE=$(awk '/MemTotal/ {printf( "%.0f\n", int ( $2 / 1024 ) + 1)}' /proc/meminfo)
if [ "${RAMSIZE}" -le "1500" ]; then
	show_dialog --msgbox "The Pentoo Installer requires a minimum of 1.5GB of RAM to run. Failing safe." 0 0
	exit 1
fi

# display welcome txt
show_dialog --textbox "${SHAREDIR}"/welcome.txt 25 75 || exit $?

# 'controller' vars
# CONFIG_LIST: One string with 0 or more items of defined FSspec:
CONFIG_LIST=
MAXSELECTION=0
SELECTION=0

# other vars
NEWSELECTION=
RETSUB=
MENU_ITEMS=

# check for settings from previous installation attempt
if settings_check; then
	# ask if old settings should be loaded
	NEWSELECTION="$(show_dialog \
        --menu "Settings from previously aborted installation detected.\nDo you want to load them?" \
		0 0 0 \
		'No' 'Start from scratch' \
		'Yes' 'Load settings (you might have to enter passwords)')"
	RETSUB=$?
	if [ "${RETSUB}" -eq 0 ] && [ "${NEWSELECTION}" = 'Yes' ]; then
		# extra check, pass menu-index of 'Prepare hard drive'
		if ! settings_checkmount 1; then
			show_dialog --msgbox "ERROR: Unable to load old settings." 0 0
			settings_shred || exit $?
		# load 'controller' vars'
		else
			SELECTION="$(settings_read 1)" || exit $?
			MAXSELECTION="$(settings_read 2)" || exit $?
			CONFIG_LIST="$(settings_read 3)" || exit $?
		fi
	else
		# remove old files
		settings_shred || exit $?
	fi
fi

while [ true ]; do
	# define menu items
	MENU_ITEMS=()
	# add only valid menu items
	[ "${MAXSELECTION}" -eq 0 ] && MENU_ITEMS+=("0" "Set Clock")
	[ "${MAXSELECTION}" -eq 1 ] && MENU_ITEMS+=("1" "Prepare Hard Drive")
	[ "${MAXSELECTION}" -eq 2 ] && MENU_ITEMS+=("2" "Copy the Distribution")
	[ "${MAXSELECTION}" -eq 3 ] && MENU_ITEMS+=("3" "Select Profile")
	[ "${MAXSELECTION}" -eq 4 ] && MENU_ITEMS+=("4" "Configure System")
	[ "${MAXSELECTION}" -eq 5 ] && MENU_ITEMS+=("5" "Install Bootloader")
	[ "${MAXSELECTION}" -eq 6 ] && MENU_ITEMS+=("6" "Exit Install")
	# expand menu items array below
	NEWSELECTION="$(show_dialog --default-item "${SELECTION}" \
        --menu "Use the UP and DOWN arrows to navigate menus.  Use TAB to switch between buttons and ENTER to select." \
		0 0 0 "${MENU_ITEMS[@]}")"
	RETSUB=$?
	if [ "${RETSUB}" -ne "0" ]; then
		show_dialog --yesno "Abort installation?" 0 0 && exit "${RETSUB}"
	fi
	# call subscript by selected item
	case "${NEWSELECTION}" in
		"0")
			"${SHAREDIR}"/settzclock
			RETSUB=$?
			;;			
		"1")
			# prepares (encrypted) partitions and returns a list of partition configs
			CONFIG_LIST="$("${SHAREDIR}"/partition_mainmenu)"
			RETSUB=$?
			;;
		"2")
			"${SHAREDIR}"/copy_distro "${CONFIG_LIST}"
			RETSUB=$?
			;;
		"3")
			"${SHAREDIR}"/setprofile "${CONFIG_LIST}"
			RETSUB=$?
			;;
		"4")
			"${SHAREDIR}"/configure_system "${CONFIG_LIST}"
			RETSUB=$?
			;;
		"5")
			"${SHAREDIR}"/install_bootloader "${CONFIG_LIST}"
			RETSUB=$?
			;;
		"6")
			echo ""
			echo "If the install finished successfully, you can now type 'reboot'"
			echo "to restart the system."
			echo ""
			exit 0 ;;
		*)
			echo "ERROR: Unexpected response '${NEWSELECTION}' in $(basename $0)" 1>&2
			exit 1
			;;
	esac
	# handle errors from sub-script/functions using a common utility function
	if ! catch_menuerror "$(basename $0)" "${NEWSELECTION}" "${RETSUB}"; then
		# everything ok, increase selection for next menu item
		SELECTION="$((NEWSELECTION+1))" || exit $?
		if [ "${MAXSELECTION}" -lt "${SELECTION}" ]; then
			MAXSELECTION="${SELECTION}"
		fi
		# write settings to temp file
		settings_write "${SELECTION}" "${MAXSELECTION}" "${CONFIG_LIST}" || exit $?
	fi
done
