#!/bin/bash
# This script is released under the GNU General Public License 3.0
# Check the COPYING file included with this distribution

# FSspec
# handler for the FSspec format defined below
# all actions with FSspec should use this

# FSspec definition
#  contains the following key-value pairs:
#   partition
#   mountpoint
#   filesystem
#	crypttype (one of: 'swap', 'luks', 'luks-gpg', '')
#   format
#   cryptname (name used by cryptsetup)
#   partuuid (PARTUUID, *not* the UUID)
#	cryptkey
#
#  mountpoint of a swap partition must be empty
#  all non swap partitions must have a mountpoint
#  root partition can only be encrypted when /boot is on another partition
#  values cannot contain white-space or the ":" character!
#
#  internal:
#   the definition is stored as one long string of key:value:key:value:...
#   order of keys is important!

# writes errors and noise to STDERR

# location of other scripts to source
readonly SHAREDIR="$(dirname ${0})" || exit $?

# source common variables, functions and error handling
source "${SHAREDIR}"/common.sh || exit $?

#############################
## START: utility functions##

# FSspec_create()
# creates an FSspec string from the input variables and writes it to STDOUT
# for external use, not all values of an FSspec are required as input
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  these items of an FSspec in this order
#   partition, mountpoint, filesystem, crypttype, format
#
FSspec_create() {
	# check input
	check_num_args "${FUNCNAME}" 5 $# || return $?
	local _PARTUUID=
	# set partuuid
	_PARTUUID="$(blkid -s PARTUUID -o value "${1}")" || return $?
	# simply call the internal create function with empty strings for missing FSspec items
	FSspec_createfull "${1}" "${2}" "${3}" "${4}" "${5}" "" "${_PARTUUID}" ""
}

# FSspec_createfull()
# creates an FSspec string from the input variables and writes it to STDOUT
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
# all items of an FSspec in correct order
#
FSspec_createfull() {
	# check input
	check_num_args "${FUNCNAME}" 8 $# || return $?
	local _PARTITION="${1}"
	local _MOUNTPOINT="${2}"
	local _FILESYSTEM="${3}"
	local _CRYPTTYPE="${4}"
	local _FORMAT="${5}"
	local _CRYPTNAME="${6}"
	local _PARTUUID="${7}"
	local _CRYPTKEY="${8}"
	local _CONFIG_SEPARATOR=':'
	# convert boolean values to 0 or 1
	[ "${_FORMAT}" != '1' ] && _FORMAT=0
	# validate
	if [ -z "${_PARTITION}" ] || [ -z "${_FILESYSTEM}" ]; then
		echo "error parsing config, partition or filesystem missing" 1>&2
		return 1
	fi
	# swap partition cannot have mountpoint
	if [ "${_FILESYSTEM}" = 'swap' ] && [ -n "${_MOUNTPOINT}" ]; then
		echo "error parsing config, swap partition cannot have mountpoint" 1>&2
		return 1
	# non swap partition, must have mountpoint
	elif [ -z "${_MOUNTPOINT}" ]; then
		echo "error parsing config, partition must have mountpoint" 1>&2
		return 1
	fi
	# validate crypttype
	if [ "${_CRYPTTYPE}" != '' ]; then
		# check crypttype
		# swap must have swap as type
		if [ "${_FILESYSTEM}" = 'swap' ] && [ "${_CRYPTTYPE}" != 'swap' ]; then
			echo "error parsing config, wrong crypttype for swap partition" 1>&2
			return 1
		elif [ "${_MOUNTPOINT}" = '/boot' ]; then
			echo "error parsing config, partition on mountpoint '/boot' cannot be encrypted" 1>&2
			return 1
		# root partition, check for /boot
		elif [ "${_MOUNTPOINT}" = '/' ]; then
			if ! FSspec_list_haskeyvalue "${CONFIG_LIST}" 'mountpoint' '/boot'; then
				echo "error parsing config, encrypted root partition requires a separate, non-encrypted partition for /boot." 1>&2
				return 1
			# check crypttype
			elif [ "${_CRYPTTYPE}" != 'luks-gpg' ]; then
				echo "error parsing config, wrong crypttype for root partition" 1>&2
				return 1
			fi
		# non-root partition, check crypttype
		elif [ "${_CRYPTTYPE}" != 'gpg' ] && [ "${_CRYPTTYPE}" != 'luks-gpg' ]; then
			echo "error parsing config, unexpected crypttype" 1>&2
			return 1
		fi
	fi


	# check partuuid
	if [ "${_PARTUUID}" != "$(blkid -s PARTUUID -o value "${_PARTITION}")" ]; then
		echo "error parsing config, partition '${_PARTITION}' does not have expected partuuid '${_PARTUUID}'" 1>&2
		return 1
		
	fi
	# everything ok, write to STDOUT and return 0
	echo -n "partition${_CONFIG_SEPARATOR}${_PARTITION}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "mountpoint${_CONFIG_SEPARATOR}${_MOUNTPOINT}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "filesystem${_CONFIG_SEPARATOR}${_FILESYSTEM}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "crypttype${_CONFIG_SEPARATOR}${_CRYPTTYPE}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "format${_CONFIG_SEPARATOR}${_FORMAT}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "cryptname${_CONFIG_SEPARATOR}${_CRYPTNAME}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "partuuid${_CONFIG_SEPARATOR}${_PARTUUID}"
	echo -n "${_CONFIG_SEPARATOR}"
	echo -n "cryptkey${_CONFIG_SEPARATOR}${_CRYPTKEY}"
	return 0
}

# FSspec_del_keyvalue()
# parses a list of FSspec and deletes all elements with key=value
# all other items from the list are printed to STDOUT
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  config_list: see defined FSscpec format
#  key: see defined FSscpec format
#  value: search for this
#
FSspec_del_keyvalue() {
	# check input
	check_num_args "${FUNCNAME}" 3 $# || return $?
	local _FIRST=1
	local _ITEM=
	local _TMPVAL=
	# loop list and output item if key=value not true
	for _ITEM in ${1}; do
		_TMPVAL="$(FSspec_parse "${_ITEM}" "${2}")" || return $? 
		if [ "${_TMPVAL}" != "${3}" ]; then
			[ "${_FIRST}" -ne 1 ] && echo -n ' '
			[ "${_FIRST}" -eq 1 ] && _FIRST=0
			echo -n "${_ITEM}"
		fi
	done
	return 0
}

# FSspec_list_haskeyvalue()
# checks if a list of FSspec has a key=value element
#
# returns 0 when found, 1 when not found
#
# parameters (required):
#  config_list: see defined FSscpec format
#  key: see defined FSscpec format
#  value: search for this
#
FSspec_list_haskeyvalue() {
	# check input
	check_num_args "${FUNCNAME}" 3 $# || return $?
	FSspec_listfind "${@}" 1>/dev/null
	return $?
}

# FSspec_listfind()
# parses a list of FSspec-strings, searches for matching key=value
# and prints first matching list item to STDOUT
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  config_list: see defined FSscpec format
#  varname: an item of the FSspec format
#  varvalue: the value to search for
#
FSspec_listfind() {
	# check input
	check_num_args "${FUNCNAME}" 3 $# || return $?
	local _CONFIG_LIST="${1}"
	local _VARNAME="${2}"
	local _VARVALUE="${3}"
	local _ITEM=
	local _TMPVALUE=
	for _ITEM in ${_CONFIG_LIST}; do
		_TMPVALUE="$(FSspec_parse "${_ITEM}" "${_VARNAME}")" || return $?
		if [ "${_TMPVALUE}" = "${_VARVALUE}" ]; then
			echo "${_ITEM}"
			return 0
		fi
	done
	# item not found, exit ungracefully
	return 1
}

# FSspec_merge()
# merges a list of old config with a list of new ones by their partition
# partitions in both lists: new config is used
# partitions which do not exist are removed
# all other items from both lists are printed to STDOUT
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  list_old_configs: list of FSspec items, see defined FSscpec format
#  list_new_configs: list of FSspec items, see defined FSscpec format
#
FSspec_merge() {
	# check input
	check_num_args "${FUNCNAME}" 2 $# || return $?
	local _LIST_OLD="${1}"
	local _LIST_NEW="${2}"
	local _LIST_RESULT=
	local _ITEM_OLD=
	local _ITEM_NEW=
	local _DEV_NEW=
	local _DEV_OLD=
	local _FOUND=
	# loop old list and add item if not found in new list
	for _ITEM_OLD in ${_LIST_OLD}; do
		_FOUND=0
		_DEV_OLD="$(FSspec_parse "${_ITEM_OLD}" 'partition')" || return $?
		# loop new list
		for _ITEM_NEW in ${_LIST_NEW}; do
			_DEV_NEW="$(FSspec_parse "${_ITEM_NEW}" 'partition')" || return $?
			if [ "${_DEV_OLD}" = "${_DEV_NEW}" ]; then
				_FOUND=1
				echo "INFO: Replacing existing config of ${_DEV_OLD}." 1>&2
				break
			fi
		done
		if [ "${_FOUND}" -eq 0 ]; then
			_LIST_NEW="${_LIST_NEW} ${_ITEM_OLD}"
		fi
	done
	# check if all partitions exist
	for _ITEM_NEW in ${_LIST_NEW}; do
		_DEV_NEW="$(FSspec_parse "${_ITEM_NEW}" 'partition')" || return $?
		if [ ! -b "${_DEV_NEW}" ]; then
			echo "INFO: Device ${_DEV_NEW} is not a valid block partition. Removing config for it." 1>&2
		else
			[ -n "${_LIST_RESULT}" ] && _LIST_RESULT="${_LIST_RESULT} "
			_LIST_RESULT="${_LIST_RESULT}${_ITEM_NEW}"
		fi
	done
	# sort result
	_LIST_RESULT="$(echo "${_LIST_RESULT}" | tr ' ' '\n' | sort | tr '\n' ' ')" || return $?
	# write result to STDOUT
	echo "${_LIST_RESULT}"
	return 0
}

# FSspec_parse()
# parses an input FSspec and writes desired var to STDOUT
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  input: see defined FSscpec format
#  varname: an item of the FSspec format
#
FSspec_parse() {
	# check input
	check_num_args "${FUNCNAME}" 2 $# || return $?
	local _ITEM="${1}"
	local _VARNAME="${2}"
	local _CONFIG_SEPARATOR=':'
	local _PARTITION=
	local _MOUNTPOINT=
	local _FILESYSTEM=
	local _CRYPTTYPE=
	local _FORMAT=
	local _CRYPTNAME=
	local _PARTUUID=
	local _CRYPTKEY=
	local _CHECKKEY=
	local _CHECKSEPS=
	# check if input has correct number of separators
	_CHECKSEPS="$(echo -n "${_ITEM//[^${_CONFIG_SEPARATOR}]}" | wc -m)" || return false;
	if [ "${_CHECKSEPS}" -ne 15 ]; then
		echo "error parsing config, wrong number of separators in '${_ITEM}'" 1>&2
		return 1
	fi
	# parse the item keys
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $1}')" || return $?
	if [ "${_CHECKKEY}" != 'partition' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $3}')" || return $?
	if [ "${_CHECKKEY}" != 'mountpoint' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $5}')" || return $?
	if [ "${_CHECKKEY}" != 'filesystem' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $7}')" || return $?
	if [ "${_CHECKKEY}" != 'crypttype' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $9}')" || return $?
	if [ "${_CHECKKEY}" != 'format' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $11}')" || return $?
	if [ "${_CHECKKEY}" != 'cryptname' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $13}')" || return $?
	if [ "${_CHECKKEY}" != 'partuuid' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	_CHECKKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $15}')" || return $?
	if [ "${_CHECKKEY}" != 'cryptkey' ]; then
		echo "error parsing config, unexpected key '${_CHECKKEY}' in '${_ITEM}'" 1>&2
		return 1
	fi
	# parse the item values
	_PARTITION="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $2}')" || return $?
	_MOUNTPOINT="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $4}')" || return $?
	_FILESYSTEM="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $6}')" || return $?
	_CRYPTTYPE="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $8}')" || return $?
	_FORMAT="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $10}')" || return $?
	_CRYPTNAME="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $12}')" || return $?
	_PARTUUID="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $14}')" || return $?
	_CRYPTKEY="$(echo ${_ITEM} | awk -F "${_CONFIG_SEPARATOR}" '{print $16}')" || return $?
	# convert boolean values to 0 or 1
	[ "${_FORMAT}" != '1' ] && _FORMAT=0
	# validate
	FSspec_createfull \
		"${_PARTITION}" \
		"${_MOUNTPOINT}" \
		"${_FILESYSTEM}" \
		"${_CRYPTTYPE}" \
		"${_FORMAT}" \
		"${_CRYPTNAME}" \
		"${_PARTUUID}" \
		"${_CRYPTKEY}" \
		&>/dev/null \
		|| return $?
	# print value to STDOUT
	case "${_VARNAME}" in
		"partition")
			echo "${_PARTITION}";;
		"mountpoint")
			echo "${_MOUNTPOINT}";;
		"filesystem")
			echo "${_FILESYSTEM}";;
		"crypttype")
			echo "${_CRYPTTYPE}";;
		"format")
			echo "${_FORMAT}";;
		"cryptname")
			echo "${_CRYPTNAME}";;
		"partuuid")
			echo "${_PARTUUID}";;
		"cryptkey")
			echo "${_CRYPTKEY}";;
		*)
			echo "Unexpected varname '${_VARNAME}' in ${FUNCNAME}()" 1>&2
			return 1 ;;
	esac
	return 0
}

# FSspec_setvalue()
# replaces the value of a key
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  input: see defined FSscpec format
#  varname: an item of the FSspec format
#  varvalue: the new value
#
FSspec_setvalue() {
	# check input
	check_num_args "${FUNCNAME}" 3 $# || return $?
	local _ITEM="${1}"
	local _VARNAME="${2}"
	local _VARVALUE="${3}"
	local _PARTITION=
	local _MOUNTPOINT=
	local _FILESYSTEM=
	local _CRYPTTYPE=
	local _FORMAT=
	local _CRYPTNAME=
	local _PARTUUID=
	local _CRYPTKEY=
	# parse the item values
	_PARTITION="$(FSspec_parse "${_ITEM}" 'partition')" || return $?
	_MOUNTPOINT="$(FSspec_parse "${_ITEM}" 'mountpoint')" || return $?
	_FILESYSTEM="$(FSspec_parse "${_ITEM}" 'filesystem')" || return $?
	_CRYPTTYPE="$(FSspec_parse "${_ITEM}" 'crypttype')" || return $?
	_FORMAT="$(FSspec_parse "${_ITEM}" 'format')" || return $?
	_CRYPTNAME="$(FSspec_parse "${_ITEM}" 'cryptname')" || return $?
	_PARTUUID="$(FSspec_parse "${_ITEM}" 'partuuid')" || return $?
	_CRYPTKEY="$(FSspec_parse "${_ITEM}" 'cryptkey')" || return $?
	# replace desired value
	case "${_VARNAME}" in
		"partition")
			_PARTITION="${_VARVALUE}" ;;
		"mountpoint")
			_MOUNTPOINT="${_VARVALUE}" ;;
		"filesystem")
			_FILESYSTEM="${_VARVALUE}" ;;
		"crypttype")
			_CRYPTTYPE="${_VARVALUE}" ;;
		"format")
			_FORMAT="${_VARVALUE}" ;;
		"cryptname")
			_CRYPTNAME="${_VARVALUE}" ;;
		"partuuid")
			_PARTUUID="${_VARVALUE}" ;;
		"cryptkey")
			_CRYPTKEY="${_VARVALUE}" ;;
		*)
			echo "Unexpected varname '${_VARNAME}' in ${FUNCNAME}()" 1>&2
			return 1 ;;
	esac
	# validate and print to STDOUT
	FSspec_createfull \
		"${_PARTITION}" \
		"${_MOUNTPOINT}" \
		"${_FILESYSTEM}" \
		"${_CRYPTTYPE}" \
		"${_FORMAT}" \
		"${_CRYPTNAME}" \
		"${_PARTUUID}" \
		"${_CRYPTKEY}" \
		|| return $?
}

# FSspec_sort()
# sort a list of FSspec-strings by the values of a key
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  config_list: see defined FSscpec format
#  varname: an item of the FSspec format
#  direction: 0 for ascending, 1 for reverse
#
FSspec_sort() {
	# check input
	check_num_args "${FUNCNAME}" 3 $# || return $?
	local _CONFIG_LIST="${1}"
	local _LIST_RESULT=
	local _VARNAME="${2}"
	local _CONFIG_SEPARATOR=':'
	local _ITEM=
	local _TMPVALUE=
	local _DIRECTION=
	[ "${3}" -eq '1' ] && _DIRECTION='-r'
	for _ITEM in ${_CONFIG_LIST}; do
		_TMPVALUE="$(FSspec_parse "${_ITEM}" "${_VARNAME}")" || return $?
		# append space
		[ -n "${_LIST_RESULT}" ] && _LIST_RESULT="${_LIST_RESULT} "
		# simply prepend the value at start
		_LIST_RESULT="${_LIST_RESULT}${_TMPVALUE}${_CONFIG_SEPARATOR}${_ITEM}"
	done
	# sort the result
	_LIST_RESULT="$(echo "${_LIST_RESULT}" | tr ' ' '\n' | sort ${_DIRECTION} | tr '\n' ' ')" || return $?
	_CONFIG_LIST=
	for _ITEM in ${_LIST_RESULT}; do
		# append space
		[ -n "${_CONFIG_LIST}" ] && _CONFIG_LIST="${_CONFIG_LIST} "
		_CONFIG_LIST="${_CONFIG_LIST}$(echo "${_ITEM}" | cut -d':' -f2-)" || return $?
	done
	# write result to STDOUT
	echo "${_CONFIG_LIST}"
	return 0
}

# FSspec_mountall()
# mounts devices to prepare installation
# also opens encrypted partitions
#
# arguments (required):
#  _CONFIG_LIST: a list of FSspec after encryption setup and mkfs
#
# exits: !=1 is an error
#
FSspec_mountall() {
	# check input
	check_num_args "${FUNCNAME}" 1 $# || return $?
	local _CONFIG_LIST="${1}"
	local _CONFIG_ITEM=
	local _PARTITION=
	local _MOUNTPOINT=
	local _FILESYSTEM=
	local _CRYPTTYPE=
	local _CRYPTNAME=
	local _CRYPTKEY=
	local _PARTPATH=
	local _UUID=
	_UUID="$(uuidgen)" || return $?
	# check if mountpoint '/' exists
	if ! FSspec_list_haskeyvalue "${_CONFIG_LIST}" 'mountpoint' '/'; then
		echo "ERROR: Root partition (with mountpoint '/') not found." 1>&2
		return 1
	fi
	# sort by mountpoint
	_CONFIG_LIST="$(FSspec_sort "${_CONFIG_LIST}" 'mountpoint' 0)" || return $?
	for _CONFIG_ITEM in ${_CONFIG_LIST}; do
		_PARTITION="$(FSspec_parse "${_CONFIG_ITEM}" 'partition')" || return $?
		_MOUNTPOINT="$(FSspec_parse "${_CONFIG_ITEM}" 'mountpoint')" || return $?
		_FILESYSTEM="$(FSspec_parse "${_CONFIG_ITEM}" 'filesystem')" || return $?
		_CRYPTTYPE="$(FSspec_parse "${_CONFIG_ITEM}" 'crypttype')" || return $?
		_CRYPTNAME="$(FSspec_parse "${_CONFIG_ITEM}" 'cryptname')" || return $?
		_CRYPTKEY="$(FSspec_parse "${_CONFIG_ITEM}" 'cryptkey')" || return $?
		_PARTPATH="${_PARTITION}"
		echo dump mount _PARTITION = "${_PARTITION}" 1>&2
		echo dump mount _MOUNTPOINT = "${_MOUNTPOINT}" 1>&2
		if [ "${_CRYPTTYPE}" != '' ]; then
			# write key to temp file
			echo "${_CRYPTKEY}" > /tmp/"${_UUID}" || return $?
			case "${_CRYPTTYPE}" in
				'swap')
					cryptsetup -c aes-xts-plain64:sha512 -s 512 -d /tmp/"${_UUID}" open --type plain "${_PARTITION}" "${_CRYPTNAME}" || return $?
					;;
				'luks-gpg')
					# key is in base64 format
					base64 -d /tmp/"${_UUID}" > /tmp/"${_UUID}".asc
					gpg --decrypt /tmp/"${_UUID}".asc | cryptsetup open --type luks "${_PARTITION}" "${_CRYPTNAME}" || return $?
					# clean up
					rm /tmp/"${_UUID}".asc || return $?
					;;
				'luks')
					cat /tmp/"${_UUID}" | cryptsetup open --type luks "${_PARTITION}" "${_CRYPTNAME}" || return $?
					;;
			esac
			# clean up
			rm /tmp/"${_UUID}" || return $?
			# use /dev/mapper
			_PARTPATH="/dev/mapper/${_CRYPTNAME}"
		fi
		# mount actions
		if [ "${_FILESYSTEM}" != 'swap' ]; then
			# create our mount directory
			mkdir -p "${DESTDIR}${_MOUNTPOINT}" || exit $?
			# mount the bad boy
			mount -t "${_FILESYSTEM}" "${_PARTPATH}" "${DESTDIR}${_MOUNTPOINT}" >>"${LOG}" 2>&1
		else
			swapon ${_PARTPATH} >>"${LOG}" 2>&1 || exit $?
		fi
	done
}

# FSspec_umountall()
# umount all items and close cryptsetup
#
# returns 0 on success
# anything else is a real error
#
# parameters (required):
#  _CONFIG_LIST: a list of FSspec after encryption setup and mkfs
#
FSspec_umountall() {
	# check input
	check_num_args "${FUNCNAME}" 1 $# || return $?
	local _CONFIG_LIST="${1}"
	local _CONFIG_ITEM=
	local _PARTITION=
	local _FILESYSTEM=
	local _CRYPTTYPE=
	local _CRYPTNAME=
	local _PARTPATH=
	# reverse sort by mountpoint
	_CONFIG_LIST="$(FSspec_sort "${_CONFIG_LIST}" 'mountpoint' 1)" || return $?
	for _CONFIG_ITEM in ${_CONFIG_LIST}; do
		_PARTITION="$(FSspec_parse "${_CONFIG_ITEM}" 'partition')" || return $?
		_FILESYSTEM="$(FSspec_parse "${_CONFIG_ITEM}" 'filesystem')" || return $?
		_CRYPTTYPE="$(FSspec_parse "${_CONFIG_ITEM}" 'crypttype')" || return $?
		_CRYPTNAME="$(FSspec_parse "${_CONFIG_ITEM}" 'cryptname')" || return $?
		_PARTPATH="${_PARTITION}"
		echo dump umount _PARTITION = "${_PARTITION}" 1>&2
		local _MOUNTPOINT=
		_MOUNTPOINT="$(FSspec_parse "${_CONFIG_ITEM}" 'mountpoint')" || return $?
		echo dump umount _MOUNTPOINT = "${_MOUNTPOINT}" 1>&2
		[ "${_CRYPTTYPE}" != '' ] && _PARTPATH="/dev/mapper/${_CRYPTNAME}"
		# ignore error when not mounted or used as swap
		# umount partition
		if [ "${_FILESYSTEM}" != 'swap' ]; then
			umount "${_PARTPATH}" 2>/dev/null
		# swapoff
		else
			swapoff "${_PARTPATH}" 2>/dev/null
			# sleep 1 to avoid error message from cryptsetup close
			# Example: device-mapper: remove ioctl on sda10 failed: Device or resource busy
			sleep 1
		fi
		if [ "${_CRYPTTYPE}" != '' ] && cryptsetup status "${_CRYPTNAME}" &>/dev/null; then
			cryptsetup close "${_CRYPTNAME}" || return $?
		fi
	done
	return 0
}


## END: utility functions##
#############################

# simpy call function based on mode
MODE="${1}"
shift
case "${MODE}" in
	'add')
		"${SHAREDIR}"/FSspec_add "${@}" ;;
	'create')
		FSspec_create "${@}" ;;
	'del_keyvalue')
		FSspec_del_keyvalue "${@}" ;;
	'edit')
		"${SHAREDIR}"/FSspec_edit "${@}" ;;
	'listfind')
		FSspec_listfind "${@}" ;;
	'list_haskeyvalue')
		FSspec_list_haskeyvalue "${@}" ;;
	'merge')
		FSspec_merge "${@}" ;;
	'parse')
		FSspec_parse "${@}" ;;
	'setvalue')
		FSspec_setvalue "${@}" ;;
	'sort')
		FSspec_sort "${@}" ;;
	'mountall')
		FSspec_mountall "${@}" ;;
	'umountall')
		FSspec_umountall "${@}" ;;
	*)
		echo "Unexpected mode '${MODE}' received, exiting ungracefully" 1>&2
		exit 1
esac
